version: 2
project_name: eniGOma

builds:
  - id: eniGOma-cli
    main: ./cmd/eniGOma/main.go
    binary: eniGOma
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
    # Removed post-hook that was using GOPATH
    # Schema files are already included in archives section
  - id: eniGOma-example
    main: ./cmd/example/main.go
    binary: eniGOma-example
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - schemas/**/*

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: coredds
    name: eniGOma
  draft: false
  prerelease: false

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
