project_name: eniGOma

builds:
  - id: eniGOma
    main: ./cmd/example/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: coredds
    name: eniGOma
    draft: false
    prerelease: false

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
