# GoReleaser configuration for enigoma
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: enigoma
    main: ./cmd/enigoma
    binary: enigoma
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/coredds/enigoma.Version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: enigoma
    builds:
      - enigoma
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - USAGE.md
      - examples/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: coredds
    name: enigoma
  prerelease: auto
  draft: false
  name_template: "enigoma v{{.Version}}"
  header: |
    # enigoma v{{.Version}}
    
    A highly customizable, Unicode-capable Enigma machine implementation in Go.
    
    ## What's Changed
  footer: |
    ## Installation
    
    ```bash
    # Install with Go
    go install github.com/coredds/enigoma/cmd/enigoma@{{.Version}}
    
    # Or download the binary for your platform below
    ```
    
    **Full documentation**: https://github.com/coredds/enigoma
